lodestar/renderer/urls.py
###########################################################################
# Lodestar is Copyright (C) 2019 Kyle Robbertze <RBBKYL001@myuct.ac.za>
#
# Lodestar is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Lodestar is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Lodestar. If not, see <http://www.gnu.org/licenses/>.
###########################################################################
from django.urls import path
from . import admin_views, doc_views, views

app_name = 'renderer'

urlpatterns = [
    path('', views.index, name='index'),
    path('textbook/<int:pk>/', views.view_textbook,
         name='view_textbook'),
    path('admin/', admin_views.index, name='admin_index'),
    path('admin/add_textbook/', admin_views.add_textbook,
         name='admin_add_textbook'),
    path('admin/textbook/<int:pk>/', admin_views.edit_textbook,
         name='admin_edit_textbook'),
    path('admin/textbook/<int:pk>/delete', admin_views.delete_textbook,
         name='admin_delete_textbook'),
    path('admin/add_ontology/', admin_views.OntologyCreate.as_view(),
         name='admin_add_ontology'),
    path('admin/ontology/<int:pk>/', admin_views.OntologyUpdate.as_view(),
         name='admin_edit_ontology'),
    path('admin/ontology/<int:pk>/default-file',
         admin_views.set_ontology_primary_file,
         name='admin_edit_ontology_primary_file'),
    path('admin/ontology/<int:pk>/delete',
         admin_views.OntologyDelete.as_view(), name='admin_delete_ontology'),
    path('docs', doc_views.Index.as_view(), name='docs_help'),
    path('docs/admin', doc_views.Admin.as_view(), name='docs_admin'),
    path('docs/user', doc_views.User.as_view(), name='docs_user'),
    path('admin/users/', admin_views.ViewUsers.as_view(),
         name='admin_view_users'),
    path('admin/user/add/', admin_views.add_user,
         name='admin_add_user'),
    path('admin/user/<int:pk>/', admin_views.edit_user,
         name='admin_edit_user'),
    path('admin/user/<int:pk>/delete', admin_views.delete_user,
         name='admin_delete_user'),
]

lodestar/urls.py
###########################################################################
# Lodestar is Copyright (C) 2019 Kyle Robbertze <RBBKYL001@myuct.ac.za>
#
# Lodestar is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Lodestar is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Lodestar. If not, see <http://www.gnu.org/licenses/>.
###########################################################################
"""lodestar URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.urls import include, path

urlpatterns = [
    path('', include('lodestar.renderer.urls')),
    path('accounts/', include('lodestar.registration.urls')),
]

lodestar/renderer/models.py
###########################################################################
# Lodestar is Copyright (C) 2019 Kyle Robbertze <RBBKYL001@myuct.ac.za>
#
# Lodestar is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Lodestar is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Lodestar. If not, see <http://www.gnu.org/licenses/>.
###########################################################################
import os

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

from lodestar import get_file_hash
from lodestar.sourceparser.models import Source

class Ontology(models.Model):
    def upload_source(instance, filename):
        file_hash = get_file_hash(instance.source_file.file).hex()
        return os.path.join('ontology', file_hash, filename)

    def upload_primary(instance, filename):
        file_hash = get_file_hash(instance.source_file.file).hex()
        return os.path.join('ontology', file_hash, filename)

    name = models.CharField(_('name'), max_length=200)
    source_file = models.FileField(upload_to=upload_source, max_length=130)
    md5sum = models.BinaryField(max_length=128, blank=True)
    definition_predicate = models.CharField(_('defintion predicate'),
                                              max_length=200)
    primary_file = models.FileField(upload_to=upload_primary, null=True, max_length=130)

    def get_absolute_url(self):
        return reverse('renderer:admin_edit_ontology', kwargs={'pk': self.pk})

    def get_root_path(self):
        return os.path.join(settings.MEDIA_ROOT, 'ontology', self.md5sum.hex())

    def __str__(self):
        return self.name

class Textbook(models.Model):
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    ontology = models.ForeignKey(Ontology, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('renderer:admin_edit_textbook', kwargs={'pk': self.pk})

    def get_absolute_view_url(self):
        return reverse('renderer:view_textbook', kwargs={'pk': self.pk})

    def __str__(self):
        return '{} by {}'.format(self.source.name, self.source.author)

lodestar/renderer/forms.py
###########################################################################
# Lodestar is Copyright (C) 2019 Kyle Robbertze <RBBKYL001@myuct.ac.za>
#
# Lodestar is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Lodestar is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Lodestar. If not, see <http://www.gnu.org/licenses/>.
###########################################################################
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import Ontology
from .widgets import UpdateFileInput

class PrimaryFileForm(forms.Form):
    primary_file = forms.ChoiceField(label=_('Primary ontology file'))

    def __init__(self, *args, **kwargs):
        file_list = kwargs.pop('file_list')
        super().__init__(*args, **kwargs)
        self.fields['primary_file'].choices = file_list

class TextbookForm(forms.Form):
    name = forms.CharField(max_length=200, label=_('Name'))
    author = forms.CharField(max_length=200, label=_('Author'))
    source_file = forms.FileField(label=_('Textbook file'),
                                  required=False,
                                  widget=UpdateFileInput)
    ontology = forms.ModelChoiceField(Ontology.objects.all(),
                                      label=_('Ontology'))

    def __init__(self, *args, require_file=True, **kwargs):
        self.require_source = require_file
        super().__init__(*args, **kwargs)

    def clean_source_file(self):
        source_file = self.cleaned_data['source_file']
        if self.require_source and not source_file:
            raise ValidationError(_('This field is required'), code='invalid')
        return source_file

class TextbookUpdateForm(TextbookForm):
    reprocess_textbook = forms.BooleanField(required=False,
                                            label=_('Reprocess annotations'))

lodestar/renderer/views.py
###########################################################################
# Lodestar is Copyright (C) 2019 Kyle Robbertze <RBBKYL001@myuct.ac.za>
#
# Lodestar is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Lodestar is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Lodestar. If not, see <http://www.gnu.org/licenses/>.
###########################################################################
import os

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.utils.translation import gettext_lazy as _

from .models import Textbook

@login_required
def index(request):
    textbooks = Textbook.objects.all()
    context = {
        'textbooks': textbooks,
        'title': _('Textbooks'),
    }
    return render(request, 'renderer/index.html', context)

@login_required
def view_textbook(request, pk):
    textbook = get_object_or_404(Textbook, id=pk)
    textbook_file = os.path.join(textbook.source.html_directory, 'index.html')

    context = {
        'title': textbook,
        'embed_file': textbook_file,
    }
    if os.path.exists(textbook_file):
        return render(request, 'renderer/view_textbook.html', context)
    return render(request, 'renderer/textbook_pending.html', context)

lodestar/renderer/templates/renderer/admin/add_update_object.html
{% extends "renderer/admin/admin_base.html" %}
{% load i18n static widget_tweaks %}

{% block extra_head %}
{{ block.super }}
{{ form.media }}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-10">
    <form action="{{ form_url }}" {% if form.is_multipart %}enctype="multipart/form-data" {% endif %}method="post">
      {% csrf_token %}
      {% for field in form %}
      {% if field.field.widget.input_type == "checkbox" %}
      <div class="form-check">
      {% else %}
      <div class="form-group">
        {% endif %}
        {% if field.field.widget.input_type == "checkbox" %}
        {{ field | add_class:'form-check-input'}}
        <label class="form-check-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% for error in field.errors %}
        <div class="alert alert-danger" role="alert">
          {{ error }}
        </div>
        {% endfor %}
        {% else %}
        <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% for error in field.errors %}
        <div class="alert alert-danger" role="alert">
          {{ error }}
        </div>
        {% endfor %}
        {% if field.field.widget.input_type == "file" %}
        {{ field | add_class:'form-control-file'}}
        {% else %}
        {{ field | add_class:'form-control' }}
        {% endif %}
        {% endif %}
      </div>
      {% endfor %}
      <div class="form-group">
        <div class="btn-group" role="group">
          <button class="btn btn-primary" id="submit-btn" type="submit">{% trans 'Save' %}</button>
          {% if delete_url %}
          <a href="{{ delete_url }}" class="btn btn-danger" id="delete-btn">{% trans 'Delete' %}</a>
          {% endif %}
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

lodestar/renderer/templates/renderer/admin/admin_base.html
{% extends "lodestar/base.html" %}
{% load i18n %}

{% block extra_head %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock blockbots%}
{% endblock extra_head %}

{% block pre_content %}
{% block breadcrumbs %}
{% if title %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'renderer:admin_index' %}">{% trans "Home" %}</a>
    </li>
    {% if intermediary_crumb %}
    <li class="breadcrumb-item">
      <a href="{{ intermediary_crumb.url }}">{{ intermediary_crumb.text }}</a>
    </li>
    {% endif %}
    <li class="breadcrumb-item active">
      {{ title }}
    </li>
  </ol>
</nav>
{% endif %}
{% endblock %}
{% block messages %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
  {{ message|capfirst }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
{% endblock messages %}
{% endblock pre_content %}

{% block content %}
{% block object-tools %}{% endblock object-tools %}
{{ content }}
{% endblock content %}

{% block post_content %}
{% block sidebar %}
<div class="row">
  <div class="col-sm">
    <h1>{% trans "My Recent Actions" %}</h1>
    {% load log %}
    {% get_admin_log 10 as admin_log for_user user %}
    {% if not admin_log %}
    <p>{% trans "None available" %}</p>
    {% else %}
    <ul class="list-group">
      {% for entry in admin_log %}
      <li class="list-group-item">
        <span class="fas fa-{% if entry.is_addition %}plus{% endif %}{% if entry.is_change %}pencil-alt{% endif %}{% if entry.is_deletion %}minus{% endif %}"></span>
        {% if entry.is_deletion or not entry.get_admin_url %}
        {{ entry.object_repr }}
        {% if entry.content_type %}
        - {% filter capfirst %}{{ entry.content_type }}{% endfilter %}
        {% else %}
        - {% trans "Unknown content" %}
        {% endif %}
        {% else %}
        <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}
          {% if entry.content_type %}
          - {% filter capfirst %}{{ entry.content_type }}{% endfilter %}
          {% else %}
          - {% trans "Unknown content" %}
          {% endif %}</a>
        {% endif %}
      </li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>
</div>
{% endblock sidebar %}
<br class="clear" />
{% endblock post_content %}

lodestar/renderer/templates/renderer/admin/delete_confirmation.html
{% extends "renderer/admin/admin_base.html" %}
{% load i18n static widget_tweaks %}

{% block content %}
<div class="row">
  <div class="col-sm-12">
    <form action="" method="post">{% csrf_token %}
      <p>{% blocktrans %}
      Are you sure you want to delete {{ object }}? There is no way of reversing
      this.
      {% endblocktrans %}</p>
      <div class="btn-group" role="group">
        <button class="btn btn-danger" id="btn-delete" type="submit">{% trans 'Delete' %}</button>
        <a href="{{ object.get_absolute_url }}" class="btn btn-secondary" id="cancel-btn">{% trans 'Cancel' %}</a>
    </form>
      </div>
      {% endblock %}

lodestar/renderer/templates/renderer/admin/index.html
{% extends "renderer/admin/admin_base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col-sm-10">
    <h1>{% trans "Textbooks" %}</h1>
  </div>
  <div class="col-sm-2">
    <a href="{% url 'renderer:admin_add_textbook' %}" class="btn btn-primary btn-heading" role="button">
      <span class="fas fa-plus"></span> {% trans "Add" %}
    </a>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    {% if textbooks %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">{% trans 'Name' %}</th>
          <th scope="col">{% trans 'Author' %}</th>
          <th scope="col">{% trans 'Ontology' %}</th>
        </tr>
        <tbody>
          {% for textbook in textbooks %}
          <tr>
            <th scope="row"><a href="{{ textbook.get_absolute_url }}">{{ textbook.source.name }}</a></th>
            <td>{{ textbook.source.author }}</th>
            <td>{{ textbook.ontology }}</th>
          </tr>
          {% endfor %}
        </tbody>
      </thead>
    </table>
    {% else %}
    {% trans "You have no textbooks" %}
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="col-sm-10">
    <h1>{% trans "Ontologies" %}</h1>
  </div>
  <div class="col-sm-2">
    <a href="{% url 'renderer:admin_add_ontology' %}" class="btn btn-primary btn-heading" role="button">
      <span class="fas fa-plus"></span> {% trans "Add" %}
    </a>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    {% if ontologies %}
    <ul class="list-group">
    {% for ontology in ontologies %}
      <li class="list-group-item">
        <a href={% url 'renderer:admin_edit_ontology' ontology.pk %}>{{ ontology }}</a>
      </li>
    {% endfor%}
    </ul>
    {% else %}
    {% trans "You have no ontologies" %}
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <h1>{% trans "Users" %}</h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    {% if users or groups %}
    <ul class="list-group">
      {% if users %}
      <li class="list-group-item">
        <div class="row">
          <div class="col-sm-8"> 
            {% trans "Users" %}
          </div>
          <div class="col-sm-2">
            <a href={% url 'renderer:admin_view_users' %} class="btn btn-primary" role="button">
              <span class="fas fa-edit"></span> {% trans "Manage" %}
            </a>
          </div>
          <div class="col-sm-2">
            <a href={% url 'renderer:admin_add_user' %} class="btn btn-secondary" role="button">
              <span class="fas fa-plus"></span> {% trans "Add" %}
            </a>
          </div>
        </div>
      </li>
      {% endif %}
      {% if groups %}
      <li class="list-group-item">
        <div class="row">
          <div class="col-sm-8"> 
            {% trans Groups %}
          </div>
          <div class="col-sm-2">
          </div>
          <div class="col-sm-2">
            <a href={% url 'renderer:admin_add_user' %} class="btn btn-secondary" role="button">
              <span class="fas fa-plus"></span> {% trans "Add group" %}
            </a>
          </div>
        </div>
      </li>
      {% endif %}
    </ul>
    {% else %}
    {% trans "You have no users to manage" %}
    {% endif %}
  </div>
</div>
{% endblock %}

lodestar/renderer/templates/renderer/admin/list_view.html
{% extends "renderer/admin/admin_base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col-sm-12">
    <ul class="list-group">
    {% for object in object_list %}
    <li class="list-group-item">
      <a href={% url edit_url object.pk %}>{{ object }}</a>
    </li>
    {% empty %}
    {{ empty_text }}
    {% endfor %}
  </div>
</div>

{% endblock %}